package thederpgamer.betterfactions.data.diplomacy.war.wargoal;

import api.common.GameCommon;
import org.schema.game.common.data.player.faction.Faction;

/**
 * [Description]
 *
 * @author TheDerpGamer
 */
public class WarGoalData {

	public enum WarGoalType {
		HUMILIATE_RIVAL("Humiliate Rival", "Humiliate a rival faction.",
					"%s:" + //Effects on this faction
					"\n - Prestige + %d" + //Increase prestige by n
					"\n - Take claimed system cost modifier: %f" + //Take a claimed system from the enemy faction
					"\n - Puppet system cost modifier: %f" + //Puppet a system from the enemy faction
					"\n - Liberate system cost modifier: %f" + //Liberate a system from the enemy faction making it independent
					"\n - Return system cost modifier: %f" + //Return a system to its original owner
					"\n - Reparations cost modifier: %f" + //Take a percentage of resources generated by the enemy faction from a system for n weeks
					"\n\n%s:" + //Effects on the enemy faction
					"\n - Prestige: %d", //Decrease prestige by n
					0.85f, 1.0f, 0.9f, 0.7f, 0.65f),
		CONTAINMENT("Containment", "Contain the enemy faction's aggressive expansion.",
					"%s:" + //Effects on this faction
					"\n - Take claimed system cost modifier: %f" + //Take a claimed system from the enemy faction
					"\n - Cannot puppet systems" + //Don't allow puppeting
					"\n - Liberate system cost modifier: %f" + //Liberate a system from the enemy faction making it independent
					"\n - Return system cost modifier: %f" + //Return a system to its original owner
					"\n - Reparations cost modifier: %f" + //Take a percentage of resources generated by the enemy faction from a system for n weeks
					"\n\n%s:" + //Effects on the enemy faction
					"\n - Take claimed system cost modifier (%d weeks): %f", //Increase their take claimed system cost modifier for n weeks
					1.0f, 0.0f, 0.6f, 0.75f, 0.5f)
		;

		public final String displayName;
		public final String description;
		public final String modifiersDescription;
		public final float takeSystemCostModifier;
		public final float puppetCostModifier;
		public final float liberateCostModifier;
		public final float returnCostModifier;
		public final float reparationsCostModifier;

		WarGoalType(String displayName, String description, String modifiersDescription, float takeSystemCostModifier, float puppetCostModifier, float liberateCostModifier, float returnCostModifier, float reparationsCostModifier) {
			this.displayName = displayName;
			this.description = description;
			this.modifiersDescription = modifiersDescription;
			this.takeSystemCostModifier = takeSystemCostModifier;
			this.puppetCostModifier = puppetCostModifier;
			this.liberateCostModifier = liberateCostModifier;
			this.returnCostModifier = returnCostModifier;
			this.reparationsCostModifier = reparationsCostModifier;
		}
	}

	/*
	public enum WarGoalType {
		TAKE_CLAIMED_SYSTEM("Take Claimed System", "Take a claimed system from the enemy faction.", 1.5f, 1.75f),
		PUPPET("Puppet", "Create a puppet government out of some or all of the enemy faction's territory.", 1.8f, 2.7f),
		DISMANTLE("Dismantle", "Free some of the enemy faction's territory from their control as independents.", 1.75f, 2.65f),
		ASSIST_ALLY("Assist Ally", "Assist an ally in a war against the enemy faction.", 1.15f, 1.25f),
		INTERVENTION("Intervention", "Intervene in a war between two or more other factions.", 1.2f, 1.3f),
		DEMAND_CONCESSIONS("Demand Concessions", "Demand concessions from the enemy faction.", 1.35f, 1.7f);

		public final String display;
		public final String description;
		public final float costModifierNPC;
		public final float costModifierPlayer;

		WarGoalType(String display, String description, float costModifierNPC, float costModifierPlayer) {
			this.display = display;
			this.description = description;
			this.costModifierNPC = costModifierNPC;
			this.costModifierPlayer = costModifierPlayer;
		}

		public static WarGoalType getWarGoalType(String warGoalType) {
			for(WarGoalType type : WarGoalType.values()) {
				if(type.name().equalsIgnoreCase(warGoalType)) return type;
			}
			return null;
		}
	}
	 */

	private final WarGoalType warGoalType;
	private final int from;
	private final int to;
	private final float score;
	private boolean demanded;

	public WarGoalData(WarGoalType warGoalType, Faction from, Faction to, float score) {
		this.warGoalType = warGoalType;
		this.from = from.getIdFaction();
		this.to = to.getIdFaction();
		this.score = score;
		this.demanded = false;
	}

	public WarGoalType getWarGoalType() {
		return warGoalType;
	}

	public Faction getFrom() {
		return GameCommon.getGameState().getFactionManager().getFaction(from);
	}

	public Faction getTo() {
		return GameCommon.getGameState().getFactionManager().getFaction(to);
	}

	public float getScore() {
		return score;
	}

	public void setDemanded(boolean demanded) {
		this.demanded = demanded;
	}
}
